### ISSUE TITLE
Design work

### ISSUE THREAD

**Issue by lukes-code** [Swatigupta-droid/Swatigupta-droid.github.io#2]
Hi, can I help with design work?

**Comment by Swatigupta-droid** [comment]
Go ahead!

**Comment by lukes-code** [comment]
Is there a username that works? I cannot see what it looks like when it works at the moment 

> Go ahead!

**Comment by Swatigupta-droid** [comment]
yes try mine!!

**Comment by Swatigupta-droid** [comment]
And do you need hacktober-accepted tags in your PRs?

**Comment by lukes-code** [comment]
Great I'll try that! Yes please, i'd really appreciate it

**Comment by Swatigupta-droid** [comment]
> Great I'll try that! Yes please, i'd really appreciate it

okay!!!

**Comment by Swatigupta-droid** [comment]
The comments are not properly visible . The almond color doesnt go well . Could you suggest a better color.?

**Comment by lukes-code** [comment]
Yes sure! No problem I will try and spruce it up a bit for you.

**Comment by Swatigupta-droid** [comment]
Perfect!!
